add modernize step to lint workflow
Signed-off-by: sivchari <shibuuuu5@gmail.com>

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -1,4 +1,4 @@
-name: golangci-lint
+name: lint
 on:
   push:
     branches:
@@ -12,7 +12,7 @@ permissions:
 
 jobs:
   golangci:
-    name: lint
+    name: golangci-lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -23,3 +23,19 @@ jobs:
         uses: golangci/golangci-lint-action@v6
         with:
           version: v1.64.8
+  modernize:
+    name: modernize
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-go@v5
+        with:
+          go-version-file: 'go.mod'
+      - name: modernize
+        run: |
+          if [ -n "$(go tool modernize -diff ./...)" ]; then
+            echo "The changes can't be modernized. Please run `go tool modernize -fix ./...`"
+            exit 1
+          fi
+          
+
